UMC-7th/Backend

build/swagger.yaml, package-lock.json, package.json, src/index.js, src/swagger/openapi.yaml
- close #1           
- Swagger 설치 및 초기 설정
어떤 변경 사항이 있나요?
=> [FEAT] #1 Swagger 기초 설정

src/controller/dummy.controller.ts, src/index.ts, src/service/dummy.service.ts, src/util/error.ts, src/util/middleware.ts
- close #8    
성공에 대한 응답, 에러 응답 핸들링 코드 추가 
어떤 변경 사항이 있나요?
=> [FEAT] #8 성공 에러 응답 핸들링

src/repository/meal.repository.ts, src/routes/meal.route.ts, src/service/meal.service.ts
- close #55 
하루 식단 조회 api 수정
어떤 변경 사항이 있나요?
=> [REFACTOR] 하루 식단 조회 api 수정

prisma/migrations/20250129154301_/migration.sql, prisma/schema.prisma, src/controller/meal.controller.ts, src/dto/meal.dto.ts, src/repository/meal.repository.ts, src/routes/meal.route.ts, src/service/meal.service.ts
- close #57          
식단 수동 추가 및 조회
어떤 변경 사항이 있나요?
=> [FEAT] #57 식단 수동 추가 및 조회

build/swagger.yaml, src/dto/deliveryAddress.dto.ts, src/dto/meal.dto.ts, src/repository/meal.repository.ts, src/routes/meal.route.ts, src/service/meal.service.ts
- close #(Isuue Num)            
어떤 변경 사항이 있나요?
=> [FEAT] 식단 api 스웨거 작성

build/swagger.yaml, src/controller/meal.controller.ts, src/routes/meal.route.ts, src/service/meal.service.ts
- close #62           
get요청에서  req.body를 req.query로 수정했습니다 ,이에 맞게 스웨거 수정했습니다
어떤 변경 사항이 있나요?
=> [REFACTOR] #62 req.body를 req.query로 수정

src/repository/meal.repository.ts, src/service/meal.service.ts
- close #63 
gpt 프롬프트 변경
어떤 변경 사항이 있나요?
=> [REFACTOR] #63 gpt 프롬프트 변경

build/swagger.yaml, package-lock.json, prisma/schema.prisma, src/dto/meal.dto.ts, src/repository/meal.repository.ts, src/service/meal.service.ts, src/util/jwt.util.ts
- close #85 
식단 난이도 int형으로 수정
어떤 변경 사항이 있나요?
=> [REFACTOR] #85 식단 난이도 int형으로 수정

build/swagger.yaml, src/controller/meal.controller.ts, src/dto/meal.dto.ts, src/index.ts, src/repository/meal.repository.ts, src/routes/meal.route.ts, src/service/meal.service.ts
- close #87         
-  userId를 jwt토큰에서 얻기
어떤 변경 사항이 있나요?
=> [REFACTOR] userId 토큰에서 추출

src/controller/meal.controller.ts, src/routes/meal.route.ts, src/service/meal.service.ts
- close #64 
- 식단 추가 컨트롤러 로직 변경
어떤 변경 사항이 있나요?
=> [REFACOTR] #64 식단 추가 컨트롤러 로직 변경

build/swagger.yaml, src/routes/user.route.ts
- close #90    
- 로그인 시 닉네임 수정하는 API 통합 (소셜 로그인과 일반 로그인 통합)
어떤 변경 사항이 있나요?
=> [FEAT] #90 닉네임 저장 API 통합

build/swagger.yaml, src/controller/meal.controller.ts, src/repository/meal.repository.ts, src/routes/meal.route.ts, src/service/meal.service.ts
- close #98 
수동 추가 식단 삭제 api 구현
어떤 변경 사항이 있나요?
=> [FEAT] 수동 추가 식단 삭제 api 구현

build/swagger.yaml, src/controller/meal.controller.ts, src/repository/meal.repository.ts, src/routes/meal.route.ts, src/service/meal.service.ts
- close #101          
즐겨찾기 식단 조회 api 구현
어떤 변경 사항이 있나요?
=> [FEAT] #101 즐겨찾기 식단 조회 

build/swagger.yaml, src/controller/meal.controller.ts, src/repository/meal.repository.ts, src/routes/meal.route.ts, src/service/meal.service.ts
- close #104        
즐겨찾기 취소 api 구현
어떤 변경 사항이 있나요?
=> [FEAT] #104 즐겨찾기 취소 api 구현

build/swagger.yaml, src/controller/meal.controller.ts, src/repository/meal.repository.ts, src/service/meal.service.ts
- close #105          
식단 생성 병렬 처리
어떤 변경 사항이 있나요?
=> [REFACOTR] 식단 생성 병렬 처리

build/swagger.yaml, package-lock.json, package.json, prisma/migrations/20250208045911_add_health_score/migration.sql, prisma/schema.prisma, src/repository/mypage.repository.ts, src/service/mypage.service.ts
- close #109 전일 대비 점수 조회 API 구현
- 전일 대비 점수 조회
어떤 변경 사항이 있나요?
- [ O ] swagger 수정
- [ O ] 기능 추가
=> [FEAT] # 109 전일 대비 점수 조회 API 구현

build/swagger.yaml, src/controller/meal.controller.ts, src/repository/meal.repository.ts, src/service/meal.service.ts
- close #69  
유저 선호식단 gpt 요청에 담기
어떤 변경 사항이 있나요?
=> [FEAT] #69 유저 선호식단 gpt 요청에 담기

prisma/migrations/20250209045557_add_profile_image/migration.sql, prisma/schema.prisma, src/repository/user.repository.ts
- close #116 
- 소셜 로그인 시 프로필 이미지 저장
어떤 변경 사항이 있나요?
=> [REFACTOR] #116 소셜 로그인 시 프로필 이미지 저장

build/swagger.yaml, src/controller/image.controller.ts, src/repository/image.repository.ts, src/service/image.service.ts
- close #102             
- 중복으로 생성되는 이미지 처리
- dall-e는 동시에 5개 이미지만 처리가 가능해서 해당 과정을 처리할 수 있는 프로세스가 필요함.
- 해당 프로세스가 구현되지 않아 db에는 "default image" 텍스트를 삽입하여 처리
어떤 변경 사항이 있나요?
=> [FEAT] #102 이미지 생성 중복 응답 처리

build/swagger.yaml, package-lock.json, src/routes/subscribe.route.ts
- close #119             
- url 구분감을 위해 구독 중인 식단 url 변경
어떤 변경 사항이 있나요?
=> [REFACTOR] #119 구독중인 식단 조회 url 변경

src/repository/subscribe.repository.ts, src/service/payment.service.ts
- close #121  
- 결제 시 DB에 저장
어떤 변경 사항이 있나요?
=> [REFACTOR] #121 결제 시 subscribe 테이블에 저장

build/swagger.yaml, package-lock.json, src/controller/subscribe.meal.controller.ts, src/repository/meal.repository.ts, src/repository/subscribe.meal.repository.ts, src/routes/index.route.ts, src/routes/meal.route.ts, src/routes/subscribe.meal.route.ts, src/service/meal.service.ts, src/service/subscribe.meal.service.ts
- close #110          
구독 식단 추가 api
어떤 변경 사항이 있나요?
=> [FEAT] 구독 식단 추가 api

src/controller/image.controller.ts, src/service/image.service.ts
- close #123            
- 이미지 생성 서비스가 동시에 5개를 초과하여 실행되면 openAI에서 오류를 발생시킨다.
- DB에 현재 몇개의 프로세스가 운영중인지 저장하고 지정된 갯수를 초과하지 않도록한다.
- 오류 발생시 프로세스 갯수를 갱신시키지 못하므로, Redis에서 유효시간을 정해 넘겨준다.
어떤 변경 사항이 있나요?
=> [FIX] #123 이미지 생성 동시성 제어

package-lock.json, src/repository/meal.repository.ts
- close #133     
즐겨찾기 식단 칼로리순 조회
어떤 변경 사항이 있나요?
=> [REFACTOR] #133 즐겨찾기 식단 칼로리순 조회

src/controller/mypage.controller.ts
- close #134          
- 유저 수정 함수 리팩토링
어떤 변경 사항이 있나요?
=> [REFACTOR] #134 유저 수정 함수 리팩토링 

src/controller/mypage.controller.ts
- close #139  
- updateImage 함수 리팩토링
어떤 변경 사항이 있나요?
=> [REFACTOR] #139 updateImage함수 리팩토링

build/swagger.yaml, src/controller/meal.controller.ts, src/repository/meal.repository.ts, src/routes/meal.route.ts, src/service/meal.service.ts
- close #141            
즐겨찾기 식단 최신순 조회
어떤 변경 사항이 있나요?
=> [FEAT] #141 즐겨찾기 식단 최신순 조회

src/controller/meal.controller.ts, src/dto/meal.dto.ts, src/repository/meal.repository.ts, src/service/meal.service.ts
- close #143             
식단 완료 리팩토링
어떤 변경 사항이 있나요?
=> 식단 완료 리팩토링

src/controller/meal.controller.ts, src/dto/meal.dto.ts, src/repository/meal.repository.ts, src/service/meal.service.ts
- close #145
- 
식단 수동 추가 리팩토링
어떤 변경 사항이 있나요?
=> [REFACTOR] #145 식단 수동 추가 리팩토링

src/controller/meal.controller.ts, src/dto/meal.dto.ts, src/repository/meal.repository.ts, src/service/meal.service.ts
- close #147 
식단 생성 리팩토링
어떤 변경 사항이 있나요?
=> [REFACTOR] #147 식단 생성 리팩토링

src/controller/meal.controller.ts, src/dto/meal.dto.ts, src/repository/meal.repository.ts, src/service/meal.service.ts
- close #150 
식단 재생성 리팩토링
어떤 변경 사항이 있나요?
=> [REFACTOR] #150 식단 재생성 리팩토링

src/controller/meal.controller.ts, src/dto/meal.dto.ts, src/repository/meal.repository.ts, src/service/meal.service.ts
- close #151      
수동 식단 api 리팩토링
어떤 변경 사항이 있나요?
=> [REFACTOR] #151 수동 식단 api 리팩토링

src/controller/meal.controller.ts, src/repository/meal.repository.ts, src/service/meal.service.ts
- close #144            
식단 즐겨찾기 api 리팩토링
어떤 변경 사항이 있나요?
=> [REFACTOR] #144 식단 즐겨찾기 api 리팩토링

src/controller/meal.controller.ts, src/routes/meal.route.ts, src/service/meal.service.ts
- close #157    
함수 재배치
어떤 변경 사항이 있나요?
=> [REFACTOR] #157 함수 재배치

src/controller/meal.controller.ts, src/repository/meal.repository.ts, src/service/meal.service.ts
- close #152        
식단 싫어요 api 리팩토링
어떤 변경 사항이 있나요?
=> [REFACTOR] #152 식단 싫어요 api 리팩토링

src/controller/meal.controller.ts, src/service/meal.service.ts
- close #160 
식단 좋아요 리팩토링
어떤 변경 사항이 있나요?
=> [REFACTOR] #160 식단 좋아요 리팩토링

src/controller/meal.controller.ts, src/controller/subscribe.meal.controller.ts, src/dto/meal.dto.ts, src/dto/subscribe.meal.dto.ts, src/repository/subscribe.meal.repository.ts, src/routes/subscribe.meal.route.ts, src/service/meal.service.ts, src/service/subscribe.meal.service.ts
- close #161         
구독 식단 api 리팩토링
어떤 변경 사항이 있나요?
=> [REFACTOR] #161 구독 식단 api 리팩토링

build/swagger.yaml, src/repository/meal.repository.ts, src/service/meal.service.ts
- close #153   
스웨거 수정
어떤 변경 사항이 있나요?
=> [REFACTOR] #153 스웨거 수정

src/controller/mypage.controller.ts
- close #165 
- mypage route 리팩토링
어떤 변경 사항이 있나요?
=> [REFACTOR] mypage route 리팩토링

src/service/mypage.service.ts
- close #167 
-  mypage 서비스 리팩토링
어떤 변경 사항이 있나요?
=> [REFACTOR] mypage 서비스 리팩토링

src/controller/image.controller.ts
- close #169         
- 식단 기본 이미지 설정
- 식단 생성 중 제공할 기본 이미지 생성
https://umc7theatthis.s3.ap-northeast-2.amazonaws.com/default/mealimg.png
어떤 변경 사항이 있나요?
=> [FEAT] #169 식단 기본 이미지 설정

src/service/mypage.service.ts
- close #171             
- 건강점수 기본값 할당
어떤 변경 사항이 있나요?
=> [FEAT] #171 건강점수 기본값 할당

src/controller/meal.controller.ts, src/repository/meal.repository.ts, src/service/meal.service.ts
- close #172  
식단 api 동시성 제어
어떤 변경 사항이 있나요?
=> [FEAT] 식단 api 동시성 제어

build/swagger.yaml, src/service/meal.service.ts
- close #176          
식단 상세 조회 응답 수정
어떤 변경 사항이 있나요?
=> [REFACTOR] #176 식단 상세 조회 응답 수정

build/swagger.yaml, src/repository/subscribe.meal.repository.ts, src/service/subscribe.meal.service.ts
- close #178          
구독 식단 상세 조회 응답값 수정
어떤 변경 사항이 있나요?
=> [REFACTOR] #178 구독 식단 상세 조회 응답값 수정

package-lock.json, package.json, src/service/mypage.service.ts
- close #175 
- 동시성 제어
어떤 변경 사항이 있나요?
=> [FEAT] #175 동시성 제어

src/controller/subscribe.controller.ts, src/repository/subscribe.repository.ts, src/routes/subscribe.route.ts, src/service/subscribe.service.ts
- close #180 
- 사용자의 장바구니 리스트를 가져오는 API를 구현
어떤 변경 사항이 있나요?
=> [FEAT] #180 장바구니 리스트 API 구현

build/swagger.yaml, src/controller/material.controller.ts, src/repository/material.repository.ts, src/routes/material.route.ts, src/service/material.service.ts
- close #185             
- 품종을 검색 받아 식재료 리스트 반환
어떤 변경 사항이 있나요?
=> [FEAT] #185 식재료 품종 검색 구현

build/swagger.yaml, src/controller/material.controller.ts, src/repository/material.repository.ts, src/routes/material.route.ts, src/service/material.service.ts
- close #187         
- 변화량을 통해 전체 식재료의 랭킹을 조회
어떤 변경 사항이 있나요?
=> [FEAT] #187 전체 식재료 랭킹 조회 구현

build/swagger.yaml, src/controller/material.controller.ts, src/repository/material.repository.ts, src/routes/material.route.ts, src/service/material.service.ts
- close #189             
- 품종별 식재료 랭킹 조회 구현
어떤 변경 사항이 있나요?
=> [FEAT] #189 품종별 식재료 랭킹 조회 구현

build/swagger.yaml, src/controller/material.controller.ts, src/repository/material.repository.ts, src/service/material.service.ts
- close #193           
- 전체 랭킹은 변동률을 기준으로, 품목별은 감소율을 기준으로 정렬
어떤 변경 사항이 있나요?
=> [FIX] #193 식재료 랭킹 기준 수정

build/swagger.yaml, package-lock.json, src/repository/meal.repository.ts, src/repository/subscribe.meal.repository.ts, src/service/meal.service.ts
- close #195         
식단 상세 조회 응답 수정
어떤 변경 사항이 있나요?
=> [REFACOTR] #195 식단 상세 조회 응답 수정
